def last_digit(a,b):
    if b==0:
        return 1
    a=a%10
    if a==0:
        return 0
    if a==1:
        return 1
    if a==2:
        if b%4==1:
            return 2
        elif b%4==2:
            return 4
        elif b%4==3:
            return 8
        elif b%4==0:
            return 6
    if a==3:
        if b%4==1:
            return 3
        elif b%4==2:
            return 9
        elif b%4==3:
            return 7
        elif b%4==0:
            return 1
    if a==4:
        if b%2==1:
            return 4
        elif b%2==0:
            return 6
    if a==5:
        return 5
    if a==6:
        return 6
    if a==7:
        if b%4==1:
            return 7
        elif b%4==2:
            return 9
        elif b%4==3:
            return 3
        elif b%4==0:
            return 1
    if a==8:
        if b%4==1:
            return 8
        elif b%4==2:
            return 4
        elif b%4==3:
            return 2
        elif b%4==4:
            return 6
    if a==9:
        if b%2==1:
            return 9
        else :
            return 1
